from selenium.webdriver import Chrome
from os import path, system
from webScrape import WebScrape
from time import sleep
dir = path.dirname(__file__)
chrome_path = path.join(dir, 'selenium','webdriver','chromedriver.exe')
webS = WebScrape()
url = 'https://bongo.cat/'
with Chrome(chrome_path,options=webS.optionsChrome(True)) as driver:
    driver.get(url)
    elmnt = driver.find_element_by_tag_name('html')
    while True:
        elmnt.send_keys('u')
        sleep(0.5)
        elmnt.send_keys('u')
        sleep(0.5)
        elmnt.send_keys('o')
        sleep(0.5)
        elmnt.send_keys('p')
        sleep(0.5)
        elmnt.send_keys('p')
        sleep(0.5)
        elmnt.send_keys('p')
        sleep(0.5)
        elmnt.send_keys('e')
        sleep(0.5)
        elmnt.send_keys('e')
        sleep(0.5)
        elmnt.send_keys('w')
        sleep(0.5)
        elmnt.send_keys('w')
        sleep(0.5)
        elmnt.send_keys('w')
        sleep(0.5)
        elmnt.send_keys('t')
        sleep(0.5)
        elmnt.send_keys('t')
        sleep(0.5)
        elmnt.send_keys('t')
        sleep(0.5)
        elmnt.send_keys('t')
        sleep(0.5)
        elmnt.send_keys('t')
        sleep(0.5)